---
- hosts: all
  become: yes
  roles:
    - base

- hosts: docker
  become: yes
  roles:
    - docker

- hosts: portainer_server
  become: yes
  roles:
    - portainer_server

- hosts: portainer_agent
  become: yes
  roles:
    - portainer_agent
