---
- name: Basic server setup
  hosts: all
  become: yes
  vars:
    will_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEFiSrlKzKmQmUvEe1YOMIq8KApjhOJFHQFjqTYCThfY will@will-macbook.local"
  tasks:
    - name: Ensure 'will' user exists
      ansible.builtin.user:
        name: will
        shell: /bin/bash
        state: present

    - name: Set authorized key for 'will'
      ansible.builtin.authorized_key:
        user: will
        key: "{{ will_ssh_key }}"
        state: present

    - name: Disable password login for 'will' and 'ansible' users
      ansible.builtin.user:
        name: "{{ item }}"
        password: "!"
      loop:
        - will
        - ansible

    - name: Allow 'will' passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/will
        content: "will ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'
