---
- hosts: all
  become: yes
  vars:
    will_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEFiSrlKzKmQmUvEe1YOMIq8KApjhOJFHQFjqTYCThfY will@will-macbook.local"
  roles:
    - base

- hosts: docker
  become: yes
  roles:
    - docker

- hosts: portainer_server
  become: yes
  roles:
    - portainer_server

- hosts: portainer_agent
  become: yes
  roles:
    - portainer_agent
