---
- name: Basic server setup
  hosts: all
  become: yes
  vars:
    will_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEFiSrlKzKmQmUvEe1YOMIq8KApjhOJFHQFjqTYCThfY will@will-macbook.local"
  tasks:
    - name: Ensure 'will' user exists
      ansible.builtin.user:
        name: will
        shell: /bin/bash
        state: present

    - name: Set authorized key for 'will'
      ansible.builtin.authorized_key:
        user: will
        key: "{{ will_ssh_key }}"
        state: present

    - name: Disable password login for 'will' and 'ansible' users
      ansible.builtin.user:
        name: "{{ item }}"
        password: "!"
      loop:
        - will
        - ansible

    - name: Allow 'will' passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/will
        content: "will ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: '0440'

    - name: Update all packages
      ansible.builtin.package:
        name: '*'
        state: latest

    - name: Install Apache web server
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Install KVM guest tools
      ansible.builtin.package:
        name:
          - qemu-guest-agent
          - spice-vdagent
        state: present

    - name: Ensure qemu-guest-agent is started and enabled
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: yes

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker repository for Debian 13
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker Community Edition
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Ensure Docker is started and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'will' to docker group
      ansible.builtin.user:
        name: will
        groups: docker
        append: yes

    - name: Install Portainer using Docker
      ansible.builtin.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        ports:
          - "8000:8000"
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data
      when: "'docker' in group_names"
